#ifndef ZRP_INPUT_VALIDATION
#ifdef ZR_ENABLE_INPUT_VALIDATION
#define ZRP_INPUT_VALIDATION 1
#else
#define ZRP_INPUT_VALIDATION 0
#endif /* ZR_ENABLE_INPUT_VALIDATION */
#endif /* ZRP_INPUT_VALIDATION */
